<?php
namespace app\components;
use app\models\ChangeForm;
use yii\base\Widget;
use Yii;
class SelectWidget extends Widget{

    public $name;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($this->name === null) $this->name = 'select';
    }

    public function run()
    {
        $model = new ChangeForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {

            if ($model['str'] == 1){
                return $this->render($this->name, compact('model'));
            }
            elseif ($model['str'] == 2){
                return $this->render($this->name, compact('model'));
            };
        };
        return $this->render($this->name, compact('model'));


    }
}